# IN CLASS LAB EXERCISES - 01

#### Import NumPy package as np

In [1]:
import numpy as np

####  01.  Create an empty array of 20 0's and replace the 4th object with the number 5

In [12]:
a=np.empty(20)
a[4]=5
print(a)

[1.54588597e-311 6.27463370e-322 0.00000000e+000 0.00000000e+000
 5.00000000e+000 5.30276956e+180 3.31033942e-033 4.57576743e-071
 5.06871944e-086 3.35860622e-143 6.01433264e+175 6.93885958e+218
 5.56218858e+180 3.94356143e+180 1.20881063e+161 4.51590354e-037
 2.62863702e-052 3.42045910e-032 6.46949594e-144 1.50008929e+248]


--------

#### 02. Create an array of 20 1's and store it as a variable named array_master. Copy the same array into another variable named array_copy

In [15]:
array_master=np.ones(20)
array_copy=array_master
print(array_copy)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


--------

#### 03.Create an array containing 30 1's and broadcast all the one's to the value 100

In [22]:
a=np.ones(30)
a[:30]=100
print(a)


[100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100.]


----------------------------------------------------

#### 04. Create an array of integers starting from 21 until 31 and name it as array1

####  ---     Create an array of integers starting from 11 until 21 and name it array2

####  ---    Calculate the difference between array1 and array2

In [25]:
array1=np.arange(21,31).reshape(5,2)
array2=np.arange(11,21).reshape(5,2)
c=array1-array2
print(c)

[[10 10]
 [10 10]
 [10 10]
 [10 10]
 [10 10]]


---------------------------------------------

#### 05. Create an array of all even integers from 2 to 10 and name it a1

#### --   Create an array of all even integers from 22 to 30 and name it a2

####    a) Use the 2 arrays as rows and create a matrix [ Hint - Use stack function from numpy ]

In [40]:
a1=np.arange(2,10,2).reshape(1,4)
a2=np.arange(22,30,2).reshape(1,4)
c=np.hstack((a1,a2))
print(c)
   


[[ 2  4  6  8 22 24 26 28]]


-----------------------

####  b) Use the 2 arrays as columns and create a matrix [ Hint - Use column_stack function from numpy ]

In [41]:
a1=np.arange(2,10,2).reshape(1,4)
a2=np.arange(22,30,2).reshape(1,4)
c=np.vstack((a1,a2))
print(c)

[[ 2  4  6  8]
 [22 24 26 28]]


--------------

#### 06. Create a 5x6 matrix with values ranging from 0 to 29 and retrieve the value intersecting at 2nd row and 3rd column

In [43]:
a=np.arange(0,30).reshape(5,6)
b=a[2,3]
print(a)
print(b)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
15


--------------------

#### 07. Create an identity matrix of shape 10x10 and replace the 0's with the value 21

In [57]:
b=np.ones(100).reshape(10,10)
c=(b*21)
print(c-(20*np.identity(10)))

[[ 1. 21. 21. 21. 21. 21. 21. 21. 21. 21.]
 [21.  1. 21. 21. 21. 21. 21. 21. 21. 21.]
 [21. 21.  1. 21. 21. 21. 21. 21. 21. 21.]
 [21. 21. 21.  1. 21. 21. 21. 21. 21. 21.]
 [21. 21. 21. 21.  1. 21. 21. 21. 21. 21.]
 [21. 21. 21. 21. 21.  1. 21. 21. 21. 21.]
 [21. 21. 21. 21. 21. 21.  1. 21. 21. 21.]
 [21. 21. 21. 21. 21. 21. 21.  1. 21. 21.]
 [21. 21. 21. 21. 21. 21. 21. 21.  1. 21.]
 [21. 21. 21. 21. 21. 21. 21. 21. 21.  1.]]


In [2]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

--------------------

#### Use NumPy to generate a random set of 10 numbers between 0 and 1

#### 08. Display a boolean array output where all values > 0.2 are True, rest are marked as False

In [60]:
a=np.random.randn(10)
print(a>0.2)

[False  True  True False  True  True  True False False False]


-------------------

#### 09. Use NumPy to generate an array matrix of 5x2 random numbers sampled from a standard normal distribution

In [67]:
a=np.random.randn(10).reshape(5,2)
print(a)

[[-0.10981053 -1.08093703]
 [ 0.10254966  0.73009638]
 [ 1.63631373 -1.11427012]
 [ 1.83930282  0.79629817]
 [ 0.39936776 -0.10423433]]


-----------------------------

#### 10. Create an array of 30 linearly spaced points between 0 and 100:

In [69]:
a=np.linspace(0,100,30)
print(a)

[  0.           3.44827586   6.89655172  10.34482759  13.79310345
  17.24137931  20.68965517  24.13793103  27.5862069   31.03448276
  34.48275862  37.93103448  41.37931034  44.82758621  48.27586207
  51.72413793  55.17241379  58.62068966  62.06896552  65.51724138
  68.96551724  72.4137931   75.86206897  79.31034483  82.75862069
  86.20689655  89.65517241  93.10344828  96.55172414 100.        ]


---------------------------

## Numpy Indexing and Selections

#### 11. Using the below given Matrix, generate the output for the below questions.

In [3]:
a=np.random.randint(20,size=(5,4))
print(a)

[[ 7 11 14 13]
 [18  9  2 17]
 [ 7 17  0  3]
 [16 12  4 19]
 [11  6 12 13]]


----------------

#### a) Retrieve the last 2 rows and first 3 column values of the above matrix using index & selection technique

In [4]:
a[3:,0:3]

array([[16, 12,  4],
       [11,  6, 12]])

------

#### b) Retrieve the value 55 from the above matrix using index & selection technique

In [91]:
a=np.arange(60).reshape(4,15)
b=a[3,10]
print(a)
print(b)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]]
55


--------------

#### c) Retrieve the values from the 3rd column in the above matrix

In [92]:
a[:,3]

array([ 3, 18, 33, 48])

---------------

#### d) Retrieve the values from the 4th row in the above matrix

In [98]:
a=np.random.randint(20,size=(5,4))
b=a[4:,]
print(b)
print(a)

[[17  6 11  5]]
[[19 19 17 16]
 [ 8 14  5 17]
 [ 2 14 19 15]
 [18 11 11  9]
 [17  6 11  5]]


-----------------

#### e) Retrieve values from the 2nd & 4th rows in the above matrix

In [99]:
a=np.random.randint(20,size=(5,4))
b=a[2:4,]
print(b)

[[19 16 18  5]
 [ 5 17  0 10]]


--------------

### Calculate the following values for the given matrix

#### a) Calculate sum of all the values in the matrix

In [107]:
a=np.random.randint(20,size=(5,4))
print(a)
np.sum(a)

[[ 2  9  8 14]
 [13 15 17 11]
 [ 8 19  4  6]
 [ 5 14  4 15]
 [15  1  2  9]]


191

--------------

#### b) Calculate standard deviation of all the values in the matrix

In [108]:
np.std(a)

5.361669516111563

------

#### c) Calculate the variance of all values in the matrix

In [109]:
np.var(a)

28.747500000000002

-----------

#### d) Calculate the mean of all values in the matrix

In [110]:
np.mean(a)

9.55

-------------

#### e) Retrieve the largest number from the matrix

In [111]:
np.max(a)

19

--------------

#### f) Retrieve the smallest number from the matrix

In [112]:
np.min(a)

1

-------

# -------------------------------- HAPPY LEARNING -------------------------------

--------------------------------